name: food_recipe
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  provider: ^6.0.5
  hive_flutter: ^1.1.0
  google_fonts: ^2.3.1
  dio: ^4.0.0
  dartz: ^0.10.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_svg: ^1.1.6
  persistent_bottom_nav_bar: ^5.0.2
  iconsax: ^0.0.8
  flutter_slidable: ^2.0.0
  share_plus: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner:

  hive_generator: ^1.1.1

flutter:

  uses-material-design: true

  assets:
    - assets/
